### ISSUE TITLE
This is awesome!  is there a path I could use to import my own .obj files?

### ISSUE THREAD

**Issue by spiraloid** [ennetws/topo-blend#2]
I have a pile of OBJ's I made that I'd love to use as a dataset, is there a way on windows to import a new folder of them and have it generate the .xml and whatever else it needs?

**Comment by ialhashim** [comment]
The data structure needed has two parts: the parts (OBJ geometry preferably watertight), the XML shape file that defines: (1) the skeletons of these parts (either as a SHEET or CURVE) and (2) their connectivity (an edge relation with parametric coordinates on the respective skeleton) and (3) group relations (mainly symmetry relations). To generate the skeletons we use our `Mean Curvature Skeletons` method. If I recall correctly the folder `nurbs_plugin` can generate a GUI interface to extract such things (there might be some external dependencies missing).

Once you have such a XML shape file and the OBJs (two examples can be found under `data/CB1_CB2`) you can perform the blending by loading the shapes in the `demo` Qt app.

Its been more than 6 years on this project so you might face compilation issues at this time. A cleaner implementation is in the newer tool found here (https://github.com/ialhashim/TopoBlender). However, the method in general is very hit and a miss.
