### ISSUE TITLE
About the UV coordinates

### ISSUE THREAD

**Issue by LeslieZhoa** [ennetws/topo-blend#3]
Thank you for your exceptional work on this project. We are interested in uploading our own mesh to create a shape blender and would like to seek your guidance on a specific aspect. Could you please explain how the UVs depicted in the attached image are obtained and what they represent?

We look forward to your response and appreciate your assistance.
![image](https://github.com/user-attachments/assets/dddc25b4-cce7-49e0-8cbd-a6722dc1c5b4)

**Comment by ialhashim** [comment]
These are points in space for the skeleton of each mesh part. It's been a long time but I believe you can find in this repo or the other one some codes and UI to help you compute such skeletons and group relationships.
